version: 2
updates:
  # Github actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    reviewers:
      - HazemMeqdad
    rebase-strategy: auto
    target-branch: master

  # Python packages
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    reviewers:
      - HazemMeqdad
    rebase-strategy: auto
    target-branch: master
